java_test(
  name = "tests",
  srcs = glob(['*.java']),
  size = "small",
  deps = [
    "//flagz-java/src/main/java/org/flagz",
    "//flagz-java/src/test/java/org/flagz/testclasses",
    "//third_party/guava",
    "//third_party/testing",
  ],
)
