package(default_visibility = ["//visibility:public"])

java_library(
    name = "flagz",
    srcs = glob(["*.java"]),
    deps = [
        "//flagz-java/src/main/java/org/flagz",
        "//third_party/etcd4j",
        "//third_party/guava",
        "//third_party/slf4j:api",
    ],
)