package(default_visibility = ["//visibility:public"])

java_library(
    name = "flagz",
    srcs = glob(["*.java"]),
    deps = [
        "//third_party/guava",
        "//third_party/jsr305",
        "//third_party/reflections",
        "//third_party/slf4j:api",
    ],
)
