package(default_visibility = ["//visibility:public"])

java_library(
  name = "testclasses",
  srcs = glob(['*.java']),
  deps = [
    "//flagz-java/src/main/java/org/flagz",
    "//third_party/guava",
    "//third_party/testing",
  ],
)
